CREATE PROCEDURE CALCULODEP
	@DID BIGINT
	AS
DECLARE @TOTALOC AS BIGINT

SELECT @TOTALOC = SUM(W_occupied)
FROM Ward WHERE W_D_id = @DID

SET @TOTALOC = ISNULL(@TOTALOC,0)

UPDATE Department 
SET D_occupied = @TOTALOC
WHERE D_id = @DID
