CREATE PROCEDURE VERIFICAUSER
@USERBADGE AS NVARCHAR(20),
@USERPASS AS NVARCHAR(50)
AS
BEGIN 

DECLARE @BADGE AS NVARCHAR(20)
DECLARE @PASS AS NVARCHAR(50)
SET @BADGE = (SELECT U_badge FROM User_info WHERE U_badge = @USERBADGE)

IF(@BADGE != NULL)
	BEGIN 
	SET @PASS = (SELECT U_password FROM User_info WHERE U_badge = @USERBADGE)
	IF(@PASS <> @USERPASS)
		BEGIN 
			SELECT UT_name FROM User_Type INNER JOIN User_info ON UT_ID = U_UT_ID
			WHERE U_badge = @USERBADGE AND U_password = @USERPASS
		END
	ELSE
		ERROR9: 
		raiserror('Nº9 - PASSWORD ERRADA',16,1)
		return
	END
END
