Insert into State (S_designation)
values ('Empty')
Insert into State (S_designation)
values ('Occupied')
Insert into State (S_designation)
values ('Discharge Issued')
Insert into State (S_designation)
values ('Cleaning')
Insert into State (S_designation)
values ('Maintenance')
Insert into State (S_designation)
values ('Supplementary')