CREATE TRIGGER VERIFY_BED_OCCUPATION 
ON dbo.BED 
AFTER Update
AS
BEGIN
	DECLARE @BSTATE AS BIGINT
	DECLARE @NSTATE AS BIGINT

	SET @BSTATE = (SELECT BED.B_S_id FROM Bed) 
	IF(@BSTATE) = 1
	BEGIN
		SELECT @NSTATE = B_S_id FROM inserted
		IF(@NSTATE != 3)
		BEGIN
		UPDATE BED SET B_S_id = @NSTATE
		WHERE B_S_id = 1
		END
	END 

END
	ERRO1: 
		ERRO1:
		RAISERROR('#1 - NÃO SÃO PERMITIDOS UPDATES',16,1)
		RETURN