CREATE TRIGGER BEDS_AVAILABLE_DEP
ON DEPARTMENT
AFTER UPDATE
AS 
BEGIN 
	DECLARE @DOC AS INT
	DECLARE @DAV AS BIGINT
	DECLARE @DID AS BIGINT

	SET @DID = (SELECT D_id FROM inserted)

	SET @DAV = (SELECT D_available FROM inserted WHERE D_id = @DID) 

	SET @DOC = (SELECT D_occupied FROM inserted WHERE D_id = @DID) 

	IF(@DAV	>= @DOC)
	BEGIN
	UPDATE Department SET D_available = @DAV
	WHERE D_id = @DID 

	UPDATE Department SET D_occupied = @DOC
	WHERE D_id = @DID
	END
END

ERRO1: 
		ERRO10:
		RAISERROR('#1 - OCCUPIED IS GREATER THAN AVAILABLE',16,1)
		RETURN