INSERT INTO dbo.Ward
VALUES (1,'General',14,10) 

INSERT INTO dbo.Ward
VALUES (2,'MALE',6,2) 

INSERT INTO dbo.Ward
VALUES (2,'FEMALE',6,1)

INSERT INTO dbo.Ward
VALUES (3,'MALE',9,4) 

INSERT INTO dbo.Ward
VALUES (3,'FEMALE',10,8)

INSERT INTO dbo.Ward
VALUES (4,'MALE',8,4) 

INSERT INTO dbo.Ward
VALUES (4,'FEMALE',7,2)

INSERT INTO dbo.Ward
VALUES (5,'MALE',6,3) 

INSERT INTO dbo.Ward
VALUES (5,'FEMALE',6,4)

INSERT INTO dbo.Ward
VALUES (6,'MALE',5,2) 

INSERT INTO dbo.Ward
VALUES (6,'FEMALE',6,2)

INSERT INTO dbo.Ward
VALUES (7,'MALE',6,4) 

INSERT INTO dbo.Ward
VALUES (7,'FEMALE',6,5)

INSERT INTO dbo.Ward
VALUES (8,'MALE',7,2) 

INSERT INTO dbo.Ward
VALUES (8,'FEMALE',7,1)

INSERT INTO dbo.Ward
VALUES (9,'MALE',6,5) 

INSERT INTO dbo.Ward
VALUES (9,'FEMALE',6,6)

INSERT INTO dbo.Ward
VALUES (10,'MALE',7,2) 

INSERT INTO dbo.Ward
VALUES (10,'FEMALE',6,3)

INSERT INTO dbo.Ward
VALUES (11,'MALE',5,2) 

INSERT INTO dbo.Ward
VALUES (11,'FEMALE',5,4)

INSERT INTO dbo.Ward
VALUES (12,'MALE',5,3) 

INSERT INTO dbo.Ward
VALUES (12,'FEMALE',5,1)

INSERT INTO dbo.Ward
VALUES (13,'MALE',6,2) 

INSERT INTO dbo.Ward
VALUES (13,'FEMALE',6,3)

INSERT INTO dbo.Ward
VALUES (14,'MALE',6,5) 

INSERT INTO dbo.Ward
VALUES (14,'FEMALE',7,1)

INSERT INTO dbo.Ward
VALUES (15,'MALE',8,2) 

INSERT INTO dbo.Ward
VALUES (15,'FEMALE',8,1)

INSERT INTO dbo.Ward
VALUES (16,'MALE',9,2) 

INSERT INTO dbo.Ward
VALUES (16,'FEMALE',9,1)

INSERT INTO dbo.Ward
VALUES (17,'MALE',9,0) 

INSERT INTO dbo.Ward
VALUES (17,'FEMALE',10,1)

INSERT INTO dbo.Ward
VALUES (18,'MALE',8,2) 

INSERT INTO dbo.Ward
VALUES (18,'FEMALE',7,0)

INSERT INTO dbo.Ward
VALUES (19,'MALE',6,1) 

INSERT INTO dbo.Ward
VALUES (19,'FEMALE',6,2)